### Send Mail
POST http://localhost:8080/api/sendMail
Content-Type: application/json

{
  "email": "jhinuk150@gmail.com",
  "name": "Jhinuk Mahanty",
  "subject": "Sendgrid email test",
  "content": "<h3>Hi,</h3><p>This is a test with sendgrid</p>"
}